### PR TITLE
Remove console method calls

### PR DESCRIPTION
**Pull request by mavnn**
This pull requests removes calls to console.log and console.error from program.fs.

It does not fully remove the Fable dependency so that the `ofPromise` function can remain; a trade off which allows Elmish to be used in none Fable contexts, but recognizes that it is still primarily a Fable project.

### CODE REVIEW

**Comment by MecuSorin** [comment]
Another approach will be to shadow it with an implementation like:
```
module console =
    let log (label, msg) = System.Console.WriteLine("{0}{1}", label, msg)
```

**Comment by et1975** [comment]
I considered using printf at some point early on, but the advantage of console.log is that it can show the arguments in a structured way. As @MecuSorin suggests, stubbing out certain fable namespaces is the way to go for now. See [Elmish.WPF](/prolucid/Elmish.WPF) for example. 
Setting up separate projects for Fable and .NET packages are in the backlog however - #116.

**Comment by forki** [comment]
Why did you close it? This makes it work on .NET + fable

**Comment by et1975** [comment]
I believe I gave a reasonable explanation, but here's another one: because if you read the contributor guidelines, I ask that you discuss the idea first. In the course of the discussion I could tell you that I made this very choice twice already and I that there's a way to addresses the cross-platform concerns in a way that doesn't sacrifice existing usability, and that's the PR I'd take gladly.

**Comment by forki** [comment]
tbf @mavnn asked on twitter and I think @alfonsogarciacaro proposed to send this solution as PR ;-)

but yes in general there should probably be a new project for .NET eventually. But if I understand alfonso correctly then thisn would compile properly in both worlds

**Comment by mavnn** [comment]
@forki  - @et1975 has a point. Asking the owner is a little different from following unsolicited twitter advice :)

The rational for keeping nice formatting of console logs makes sense, and taking a source reference and patching in the same way as Elmish.WPF would work in the short term.

**Comment by alfonsogarciacaro** [comment]
Yeah, sorry, it was me who suggested to send the PR. That's the problem of mixing media for software discussions ;)

`Console.WriteLine(string)` will be compiled to `console.log` by Fable (if there are more arguments, Fable formatting will be applied). But I agree this is a Fable implementation detail and we shouldn't trust it forever (btw, `Console.Error` is not supported). Another solution for cross platform targeting is the `Emit` attribute:

```fsharp

type Console =
    [<Emit("console.log({0...})">]
    static member Log([<ParamArray>] args) = System.Console.WriteLine(args) // or similar
```

Fable will use `Emit` while .NET will use the body function. This won't remove the Fable.Core dependency although the attribute is recognized just by name so it'd be possible to define `Fable.Core.EmitAttribute` within Elmish, but this feels admittedly hacky.

The proper functional solution would be to pass the log function as a parameter but this would imply changing most of Elmish client. A less nice solution would be to make it a settable value somewhere (with `Console.WriteLine` as default) and let `Elmish.Browser` set it to `fun msg x -> console.log(msg, toPlain x)`.

**Pull request closed without merging**
