### PR TITLE
Added Fifteen Puzzle sample

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Here is one more :smile: [fifteen puzzle](https://en.wikipedia.org/wiki/15_puzzle)

fifteen-puzzle gif

### CODE REVIEW

**Comment by et1975** [comment]
This is awesome, but to me the samples we host in elmish repo demonstrate an essential aspect of the lib, maybe you could host advanced samples like these in your own repo?
@alfonsogarciacaro  I think it's time we start awesome-fable list and link it from there.

**Comment by forki** [comment]
I think we should create an official samples repo. I love the PR process
for samples, but yes maintenance of all samples doesn't need to be in main
repo. So we don't need to upgrade all the samples all the time.

Am 15.04.2017 3:17 vorm. schrieb "Eugene Tolmachev" <
notifications@github.com>:

**Comment by alfonsogarciacaro** [comment]
Related to https://github.com/fable-compiler/Fable/issues/811

Yes, I was thinking about that for the issue above :point_up: Whether it was better to keep such a list in a page in Fable's web, a repo with a README or just a Wiki page (so community members can freely edit it).

That said, if we had a web page like the one @MangelMaxime did for fable-arch where samples can be easily added, I think apps like this one are a very good showcase that users can play with without installing anything. This is very important when programmers are comparing different frameworks and compile-to-JS languages in the internet. That web could be in this repo or a separate one for easier maintenance.

**Comment by alfonsogarciacaro** [comment]
The other option, as fable-elmish is now our officially recommended library to build SPAs with Fable, is to have a section dedicated to fable-elmish in Fable website and put the sample there. I actually want to rewrite Fable website in elmish following fable-arch web model :+1:

**Comment by Zaid-Ajaj** [comment]
So it comes down to two options: 
 - Create a repo with the samples inside the repo
   - Have the repos in there share dependencies vs. Having independent directories for each sample
 - Create a page (wiki, awesome-fable, docs site) and reference samples via links to their own respective repos
   - Every sample can then publish a demo for each repo in it's own gh-pages branch, this way you can reference a "live" preview from the docs site for example in an `iframe` just like @MangelMaxime was doing with fable-arch

To me, the second option is the way to go. What do you think?

**Comment by forki** [comment]
Yes we need a separate repo that has a build script that allows to build all samples. And a deploy step that pushes this site to github pages. We then add back links to the original code on github and advertise the sample site like crazy. 

So people can learn about it and see code on github.

Ideally the sample site is subpage of the official docs.

**Comment by et1975** [comment]
Now that we're in our own org, every member can create own a repo here. I'd like to see elm-like project structure, where a single sample/lib has a dedicated github project.

**Pull request closed without merging**
