### PR TITLE
Subscriptions typo

### PR DESCRIPTION
**Pull request by blair55**
Make code sample reflect description

### CODE REVIEW

**Comment by et1975** [comment]
Ha, good catch! 
However, it would fail to compile, `Program.mkSimple` does not actually expect tuple in the signature...
Let me see, perhaps I better update the description :)

**Comment by et1975** [comment]
Updated the docs, what do you think?

**Comment by blair55** [comment]
That's a clean, pure example.

One typo tho: convinience -> convenience

Thanks! :)

**Comment by et1975** [comment]
Thank you, closing.

**Pull request closed without merging**
